const opcodes = {
    "ACI": "CE",
    "ADC A": "8F",
    "ADC B": "88",
    "ADC C": "89",
    "ADC D": "8A",
    "ADC E": "8B",
    "ADC H": "8C",
    "ADC L": "8D",
    "ADC M": "8E",
    "ADD A": "87",
    "ADD B": "80",
    "ADD C": "81",
    "ADD D": "82",
    "ADD E": "83",
    "ADD H": "84",
    "ADD L": "85",
    "ADD M": "86",
    "ADI": "C6",
    "ANA A": "A7",
    "ANA B": "A0",
    "ANA C": "A1",
    "ANA D": "A2",
    "ANA E": "A3",
    "ANA H": "A4",
    "ANA L": "A5",
    "ANA M": "A6",
    "ANI": "E6",
    "CALL": "CD",
    "CC": "DC",
    "CM": "FC",
    "CMA": "2F",
    "CMC": "3F",
    "CMP A": "BF",
    "CMP B": "B8",
    "CMP C": "B9",
    "CMP D": "BA",
    "CMP E": "BB",
    "CMP H": "BC",
    "CMP L": "BD",
    "CMP M": "BE",
    "CNC": "D4",
    "CNZ": "C4",
    "CP": "F4",
    "CPE": "EC",
    "CPI": "FE",
    "CPO": "E4",
    "CZ": "CC",
    "DAA": "27",
    "DAD B": "09",
    "DAD D": "19",
    "DAD H": "29",
    "DAD SP": "39",
    "DCR A": "3D",
    "DCR B": "05",
    "DCR C": "0D",
    "DCR D": "15",
    "DCR E": "1D",
    "DCR H": "25",
    "DCR L": "2D",
    "DCR M": "35",
    "DCX B": "0B",
    "DCX D": "1B",
    "DCX H": "2B",
    "DCX SP": "3B",
    "DI": "F3",
    "EI": "FB",
    "HLT": "76",
    "IN": "DB",
    "INR A": "3C",
    "INR B": "04",
    "INR C": "0C",
    "INR D": "14",
    "INR E": "1C",
    "INR H": "24",
    "INR L": "2C",
    "INR M": "34",
    "INX B": "03",
    "INX D": "13",
    "INX H": "23",
    "INX SP": "33",
    "JC": "DA",
    "JM": "FA",
    "JMP": "C3",
    "JNC": "D2",
    "JNZ": "C2",
    "JP": "F2",
    "JPE": "EA",
    "JPO": "E2",
    "JZ": "CA",
  };
  
  export default opcodes;
  